Repository CSwala/awesome-career-pages, pull requests merged in 2021-04, with the labels that each got.

#23 Adding Companies
  Portal.json
  README.md
Labels: Level0, gssoc21

#24 Added 25 companies
  Portal.json
  README.md
Labels: Level1, gssoc21

#26 Fix#25: Add 5 companies
  Portal.json
  README.md
Labels: Level0, gssoc21

#34 added 25 companies
  Portal.json
  README.md
Labels: Level2, gssoc21

#40 Fix #39: Changes in Portal.json
  Portal.json
Labels: Level0, gssoc21

#45 added 5 more companies
  Portal.json
  README.md
Labels: Level0, gssoc21
